### ISSUE TITLE
Test AF

### ISSUE THREAD

**Issue by mencattini** [cui-unige/ctl-mencattini#1]
Hello,

J'ai une question concernant le test sur `AF`. En effet, j'ai essayé de coder quelque chose pour le `EG`, et retourner le resultat. Cependant le test ne passait pas, alors que la valeur que je renvoyais était `false`.

Du coup j'ai tenté de faire:
```lua
  elseif formula [Adt.Operation] == Expression.EG then
    -- FIXME: evaluate EG
    return false
```

et malgré cela j'ai toujours une erreur:
```bash
Failure → src/ctl/init_spec.lua @ 86
#ctl can prove finally
src/ctl/init_spec.lua:107: Expected to be falsy, but value was:
(boolean) true

stack traceback:
	src/ctl/init_spec.lua:107: in function <src/ctl/init_spec.lua:86>
```

Je me demandais si j'ai loupé qqch ou s'il y a un problème quelque part

**Comment by saucisson** [comment]
La formule est traduite en

```
Not { 1 = EG { 1 = Not { 1 = Atomic { 1 = function: 0x00747370 }: expression }: expression }: expression }: expression
```

Lorsque je met: `initial.properties[formula] = true` dans le corps de `EG`, le test ligne 105 est faux.
Lorsque je met: `initial.properties[formula] = false` dans le corps de `EG`, le test ligne 106 est faux.

Donc ça semble cohérent, non ?

**Comment by mencattini** [comment]
Oui, mais pourquoi le test échoue?
Si on pose
`initial.properties[formula] = false`
Avec les tests suivants (ligne 105,106 du `init_spec.lua`):
```
    assert.is_truthy (Ctl (true_formula , Reachability (philosophers)))
    assert.is_falsy  (Ctl (false_formula, Reachability (philosophers)))
```
Les deux tests devraient passer.

**Comment by mencattini** [comment]
Autre question:
comment peut-on parcourir les successeurs d'un état donné?
Peut-on utiliser l'attribut `successor` de l'état?

**Comment by saucisson** [comment]
L'un des tests vérifie si la formule est évaluée à vrai, l'autre si elle est évaluée à false. Donc, avec `initial.properties[formula] = false`, il n'y en a qu'un des deux qui peut passer.
Ou alors je rate quelque chose...

**Comment by saucisson** [comment]
Oui, comme dans le TP1, on peut itérer sur les successeurs d'un état avec l'attribute `successors [transition]`.

**Comment by mencattini** [comment]
Effectivement, je me suis embrouillé.

Merci pour les deux réponses.
